#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# texaccents
#
# purpose:  remove non-ASCII characters and replace them with TeX codes
# license:  MIT License
# author:   François-Xavier Coudert
# e-mail:   fxcoudert@gmail.com
#


# Table of combining accents and their LaTeX equivalent
combiningAccents = {
    "\u0300": "\\`",  # grave
    "\u0301": "\\'",  # acute
    "\u0302": "\\^",  # circumflex
    "\u0303": "\\~",  # tilde
    "\u0304": "\\=",  # macron
    "\u0306": "\\u",  # breve
    "\u0307": "\\.",  # dot above
    "\u0308": '\\"',  # diaresis
    "\u030A": '\\r',  # ring above
    "\u030B": '\\H',  # double acute
    "\u030C": '\\v',  # caron
    "\u0323": '\\d',  # dot below
    "\u0327": '\\c',  # cedilla
    "\u0328": '\\k',  # ogonek
    "\u0331": '\\b',  # macron below
}


# Replacement for non-ASCII characters
nonASCII = {
    "æ": "{\\ae}",
    "Æ": "{\\AE}",
    "ð": "{\\dh}",
    "Ð": "{\\DH}",
    "þ": "{\\th}",
    "Þ": "{\\TH}",
    "ı": "{\\i}",
    "ȷ": "{\\j}",
    "ł": "{\\l}",
    "Ł": "{\\L}",
    "Ŋ": "{\\NG}",
    "ŋ": "{\\ng}",
    "œ": "{\\oe}",
    "Œ": "{\\OE}",
    "ø": "{\\o}",
    "Ø": "{\\O}",
    "ß": "{\\ss}",
    "–": "--",  # Dashes
    "—": "---",
    "−": "--",
    "¡": "{!`}",  # Punctuation
    "¿": "{?`}",
    "·": "\\cdotp",
    "≥": "$\\ge$",  # Math operators
    "≤": "$\\le$",
    "≠": "$\\neq$",
    "∼": "\\~",
    "©": "\\copyright",  # Misc
    "°": "$\\deg$",
    "α": "$\\alpha$",  # Greek
    "β": "$\\beta$",
    "γ": "$\\gamma$",
    "δ": "$\\delta$",
    "ε": "$\\epsilon$",
    "η": "$\\eta$",
    "θ": "$\\theta$",
    "λ": "$\\lambda$",
    "µ": "$\\mu$",
    "ν": "$\\nu$",
    "π": "$\\pi$",
    "σ": "$\\sigma$",
    "τ": "$\\tau$",
    "φ": "$\\phi$",
    "χ": "$\\chi$",
    "ψ": "$\\psi$",
    "ω": "$\\omega$",
    "‘": "`",  # Quotes
    "’": "'",
    "“": "``",
    "”": "''",
    "′": "$^\\prime$",
    "‚": ",",  # Weird characters
    "„": ",,",
    "\xa0": " ",  # Unprintable characters
}


def replace_accents(s):
    """Replaces combining accents by corresponding TeX macros"""

    import unicodedata
    s = unicodedata.normalize('NFD', s)
    res = ""
    b = s[0]
    for c in s[1:]:
        if unicodedata.combining(c) and c in combiningAccents:
            if b == "i" or b == "j":
                b = "\\" + b
            b = combiningAccents[c] + "{" + b + "}"
        else:
            res += b
            b = c
    return unicodedata.normalize('NFC', res + b)


def texaccents(s):
    """Replaces non-ASCII characters in string by TeX commands"""

    s = "".join([nonASCII[c] if c in nonASCII else c for c in s])
    s = replace_accents(s)
    return s


def main():
    import codecs
    import locale
    import sys

    # Set our output to the right encoding if none was chosen
    if sys.stdout.encoding is None:
        sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout)

    if len(sys.argv) > 1:
        print("\nUsage: texaccents <infile >outfile\n")
        sys.exit(1)

    for s in sys.stdin.readlines():
        print(texaccents(s), end='')


if __name__ == '__main__':
    main()
