#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# text2doi
#
# purpose:  get DOI from references in text format (one per line)
# license:  MIT License
# author:   François-Xavier Coudert
# e-mail:   fxcoudert@gmail.com
#

import codecs
import locale
import requests
import sys


def main():

    # Set our output to the right encoding if none was chosen
    if sys.stdout.encoding is None:
        sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout)

    for s in sys.stdin.readlines():
        s = s.strip()
        if len(s) == 0:
            continue

        try:
            print(getDOI(s))
        except Exception:
            print("Reference not found: " + s)


def getDOI(s):
    p = {"q": s, "sort": "score"}
    r = requests.get("https://search.crossref.org/dois", params=p)
    return r.json()[0]["doi"]


if __name__ == '__main__':
    main()
