#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# unicode
#
# purpose:  display the characters in a Unicode string
# license:  MIT License
# author:   François-Xavier Coudert
# e-mail:   fxcoudert@gmail.com
#

import sys
import unicodedata
import wcwidth

for c in sys.stdin.read():
    if ord(c) > 0xFFFF:
        print(f'U+{ord(c):06X}', end='')
    elif ord(c) > 0xFF:
        print(f'  U+{ord(c):04X}', end='')
    else:
        print(f'    U+{ord(c):02X}', end='')

    cat = unicodedata.category(c)
    if cat == 'Cc' or cat == 'Cn':
        print()
        continue

    print('  ' + c, end=' ' * (4 - wcwidth.wcwidth(c)))

    try:
        print(unicodedata.name(c))
    except Exception:
        print()
